export enum Locations {
  'Bueno Ravine',
  'Frigid Knot',
  'Orbituary',
  'The Golden Riviera',
  'Checkmate',
  'Dudley & Daughters',
  'Endgame',
  'Gaslight',
  'Megumi Refueling',
  'Arid Reach',
  "Jackson's Swap",
  'Sunset Mesa',
  'Patch City',
  'Rustville',
  'Ashland',
  "Kabir's Outpost",
  "Chawla's Beach",
  'Fallow Field',
  "Goner's Deal",
  "Sacren's Plot",
  "Seer's Canyon",
  "Rat's Nest",
  "Rod's Fuel 'N Supplies",
  'Starlight Service Station',
  'Blackrock Exchange',
  'Canard View',
  'Last Landings',
  'Rough Landing',
  'Ruin Station',
  'ARC-L1 Wide Forest Station',
  'ARC-L2 Lively Pathway Station',
  'ARC-L3 Modern Express Station',
  'ARC-L4 Faint Glen Station',
  'ARC-L5 Yellow Core Station',
  'Area18',
  'Baijini Point',
  'Humboldt Mines',
  'Loveridge Mineral Reserve',
  'Paradise Cove',
  'Shubin Mining Facility SAL-2',
  'Shubin Mining Facility SAL-5',
  'The Orphanage',
  'ArcCorp Mining Area 045',
  'ArcCorp Mining Area 048',
  'ArcCorp Mining Area 056',
  'ArcCorp Mining Area 061',
  "Samson & Son's Salvage Center",
  'Shady Glen Farms',
  'CRU-L1 Ambitious Dream Station',
  'CRU-L4 Shallow Fields Station',
  'CRU-L5 Beautiful Glen Station',
  'Gallete Family Farms',
  'Hickes Research Outpost',
  'PRIVATE PROPERTY',
  'Terra Mills HydroFarm',
  'Tram & Myers Mining',
  'ArcCorp Mining Area 141',
  'Bountiful Harvest Hydroponics',
  "Brio's Breaker Yard",
  'Jumptown',
  'Kudre Ore',
  'Nuen Waste Management',
  'Shubin Mining Facility SCD-1',
  'Orison',
  'Seraphim Station',
  'Seraphim Station > Dumpers Depot',
  'ArcCorp Mining Area 157',
  'Benson Mining Outpost',
  'Deakins Research Outpost',
  'Grim HEX',
  'Grim HEX > Dumpers Depot',
  'NT-999-XX',
  'HUR-L1 Green Glade Station',
  'HUR-L2 Faithful Dream Station',
  'HUR-L3 Thundering Express Station',
  'HUR-L4 Melodic Fields Station',
  'HUR-L5 High Course Station',
  'HDMS-Anderson',
  'HDMS-Norgaard',
  'HDMS-Bezdek',
  'HDMS-Lathan',
  'Cutter’s Rig',
  'Everus Harbor',
  'Finn’s Folly',
  'HDMS-Edmond',
  'HDMS-Hadley',
  'HDMS-Oparei',
  'HDMS-Pinewood',
  'HDMS-Stanhope',
  'HDMS-Thedus',
  'Covalex Distribution Centre S1DC06',
  'Dupree Industrial Manufacturing Facility',
  'Greycat Stanton I Production Complex-B',
  'Sakura Sun Magnolia Workcenter',
  'HDPC-Casillo',
  'HDPC-Farnesway',
  'HDMS-Ryder',
  'HDMS-Woodruff',
  'Lorville',
  'Ludlow',
  'HDMS-Hahn',
  'HDMS-Perlman',
  "Maker's Point",
  'Pickers Field',
  'Rappel',
  'Reclamation & Disposal Orinth',
  'Weeping Cove',
  'Zephyr',
  'MIC-L1 Shallow Frontier Station',
  'Xenothreat-SecurityStation',
  'MIC-L2 Long Forest Station',
  'MIC-L3 Endless Odyssey Station',
  'MIC-L4 Red Crossroads Station',
  'MIC-L5 Modern Icarus Station',
  'Magnus Gateway',
  'Pyro Gateway',
  'Terra Gateway',
  'Astor’s Clearing',
  'Bloodshot Ridge',
  'Rayari Anvik Research Outpost',
  'Rayari Kaltag Research Outpost',
  'Shubin Mining Facility SMCa-6',
  'Shubin Mining Facility SMCa-8',
  'Rayari Cantwell Research Outpost',
  'Rayari McGrath Research Outpost',
  'Dunboro',
  "Bud's Growery",
  'Devlin Scrap & Salvage',
  'Frostbite',
  'Harper’s Point',
  'Moreland Hills',
  'Covalex Distribution Centre S4DC05',
  'Cry-Astro Processing Plant 34-12',
  'Sakura Sun Goldenrod Workcenter',
  'Cry-Astro Processing Plant 19-02',
  'Microtech Logistics Depot S4LD13',
  'Microtech Logistics Depot S4LD01',
  'Greycat Stanton IV Production Complex A',
  'New Babbage',
  'Outpost 54',
  'Port Tressler',
  "Raven's Roost",
  'Rayari Deltana Research Outpost',
  'Razor’s Edge',
  'Shubin Mining Facility SM0-10',
  'Shubin Mining Facility SM0-13',
  'Shubin Mining Facility SM0-18',
  'Shubin Mining Facility SM0-22',
  'The Necropolis',
}
